# Content customization
# ---------------------------------------------------------------
title: Azure Mist
footer_message: Your footer message
# Optional Footer URL. Omit to not show a link
#footer_url: none